CREATE DATABASE collage;
USE collage;


CREATE TABLE student(
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);


INSERT INTO student VALUES(
101,"SHUBHAM YADAV",21
);


INSERT INTO student VALUES(
102,"kishan yadav",17
);

SELECT * FROM student;

CREATE DATABASE IF NOT EXISTS collage;
DROP DATABASE IF EXISTS COLLAGES;

SHOW DATABASES;
SHOW TABLES;


DROP TABLE student;

CREATE TABLE student(
rollno INT PRIMARY KEY,
name VARCHAR(50)
);


INSERT INTO student(rollno,name)
VALUES
(101,'SHUBHAM YADAV'),
(102,'KISHAN YADAV');
INSERT INTO student VALUES (103,'RAM');


SELECT * FROM student;

CREATE DATABASE IF NOT EXISTS XYZ_Comapny;
USE XYZ_Comapny;
CREATE TABLE employee_info(
id INT PRIMARY KEY,
name VARCHAR(50),
salary INT NOT NULL
);

INSERT INTO employee_info(id , name , salary)
VALUES
(1,'ADAM',25000),
(2,'BOB',30000),
(3,'CASEY',40000);

SELECT * FROM employee_info;
SELECT name FROM employee_info;
SELECT salary, name FROM employee_info;

CREATE TABLE temp1(
id INT UNIQUE
);
INSERT INTO temp1 VALUES(101);
INSERT INTO temp1 VALUES(101);


CREATE DATABASE IF NOT EXISTS collage1;
USE collage1;
CREATE TABLE student(
rollno INT PRIMARY KEY,
name VARCHAR(50),
marks INT NOT NULL,
grade VARCHAR(1),
city VARCHAR(20)
);
